version: '3.8'

services:
  streamlit:
    build:
        dockerfile: ./Dockerfile
        context: ./
    ports:
        - '8501:8501'
    volumes:
        - type: bind
          source: ./app.py
          target: /app/app.py
      
    command: streamlit run app.py